version: '3'
services:
  frontend:
    build:
      context: ./my-frontend
    ports:
      - "80:80"
    networks:
      - my_network

  backend:
    build:
      context: ./backend_server
    ports:
      - "3000:3000"
    environment:
      - SECRETKEY=${SECRETKEY}
      - MONGO_URL=${MONGO_URL}
    networks:
      - my_network

networks:
  my_network:
